language: generic
sudo: required
services:
  - docker

#before_install:
#  - docker build -t appelsappel/react-test -f ./client/Dockerfile.dev ./client

#script:
#  - docker run appelsappel/react-test npm test

script:
  - docker build -t appelsappel/multi-client-a ./client
  - docker build -t appelsappel/multi-nginx-a ./nginx
  - docker build -t appelsappel/multi-api-a ./api
  - docker build -t appelsappel/multi-worker-a ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push appelsappel/multi-client-a
  - docker push appelsappel/multi-nginx-a
  - docker push appelsappel/multi-api-a
  - docker push appelsappel/multi-worker-a

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: elasticbeanstalk-us-east-2-331856745095
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

