language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t appelsappel/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run appelsappel/react-test npm test

after_success:
  - docker build -t appelsappel/multi-client ./client
  - docker build -t appelsappel/multi-client ./nginx
  - docker build -t appelsappel/multi-client ./api
  - docker build -t appelsappel/multi-client ./worker

- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

- docker push appelsappel/multi-client
- docker push appelsappel/multi-nginx
- docker push appelsappel/multi-api
- docker push appelsappel/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Docker-env"
  bucket_name: elasticbeanstalk-us-east-2-331856745095
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

