version: '3' #staat in elke docker-compose.yml file
services:
  postgres: # name of the service
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    depends_on:
      - postgres
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    volumes: #
      - /app/node_modules #leave this folder as is
      - ./api:/app # if you change stuff in api, reflect inside container
    environment:
      - REDIS_HOST=redis #service name
      - REDIS_PORT=6379 #default redis port
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules #leave this folder as is
  worker:
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules #leave this folder as is
      - ./worker:/app
